config/routes.rb
Rails.application.routes.draw do
  resources :phrases
  get 'homes/index'
  resources :targets
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :targets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    # @targets = Target.all
    @targets = Target.where(user_id: current_user.id)
    
    # Phraseのidを全件取得
    # phrase_ids = Phrase.select('id')
    # 取得したidを配列に入れる

    # # pluckを使用した方法で、以下のようにできないか？
    # phrase_ids = Phrase.pluck(:id)
    # @phrase = Phrase.find(rand(phrase_ids))

    # 配列に入れたidの中からランダムにidを取り出す
    @phrase = Phrase.find(rand(Phrase.first.id..Phrase.last.id))
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: %i[ show edit update destroy ]

  # GET /phrases or /phrases.json
  def index
    @phrases = Phrase.all
  end

  # GET /phrases/1 or /phrases/1.json
  def show
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases or /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: "Phrase was successfully created." }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1 or /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: "Phrase was successfully updated." }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1 or /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url, notice: "Phrase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phrase_params
      params.require(:phrase).permit(:content, :personage)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      flash[notice] = 'ログインしました'
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy ]

  # GET /targets or /targets.json
  def index
    @targets = Target.where(user_id: current_user.id)
    binding.irb
  end

  # GET /targets/1 or /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets or /targets.json
  def create
    @target = Target.new(target_params)
    @target.user_id = current_user.id

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: "Target was successfully created." }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1 or /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: "Target was successfully updated." }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1 or /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: "Target was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def target_params
      params.require(:target).permit(:age, :goal)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :birthday, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="container">
  <div class="set_center_outer">
    <div class="set_center_inner">
      <blockquote>
        <p><%= @phrase.content %></p>
        <% if @phrase.present? %>
          <p><%= @phrase.personage %></p>
        <% end %>
      </blockquote>
    </div>
  </div>

    <% @targets.each do |target| %>
        <div class="card bg-light mb-3" style="width: 32rem;">
          <div class="card-header"><%= target.age %>才まで</div>
          <% if target.goal.present? %>
            <div class="card-body">
              <h5 class="card-title">目標</h5>
              <p class="card-text"><%= target.goal %></p>
              <p class="until">目標期限まで</p>
              <p class="timer">あと
              <span id="hour"></span>時間
              <span id="min"></span>分
              <span id="sec"></span>秒
              <p>そのためにいまこの時間を何に使いますか？</p>
              </p>
            </div>
          <% end %>
        </div>
    <% end %>


      <div class="new_buttom">
        <%= link_to 'Target新規登録', new_target_path, class:"btn btn-outline-dark" %>
        <%= link_to 'Phrase新規登録', new_phrase_path, class:"btn btn-outline-dark" %>
      </div>


<p>日々の学びの中で"シビれた"名言を登録していこう！</p>

</div>




<script>

function countdown(){
const now=new Date();//今の時間
const tomorrow=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);//明日の0:00
const differ=tomorrow.getTime()-now.getTime();//あと何秒か計算


const sec=Math.floor(differ/1000)%60;//ミリ秒を秒に直してから
const min=Math.floor(differ/1000/60)%60;//1時間=60分だからね
const hour=Math.floor(differ/1000/60/60);


document.getElementById("hour").textContent=String(hour).padStart(2,"0"); //一桁になった時0がつくように
document.getElementById("min").textContent=String(min).padStart(2,"0")
document.getElementById("sec").textContent=String(sec).padStart(2,"0")
setTimeout(countdown,1000);//1秒毎に繰り返す
}
countdown();






// function set2fig(num) {
//   // 数値が1桁だったら2桁の文字列にして返す
//   var ret;
//   if( num < 10 ) { ret = "0" + num; }
//   else { ret = num; }
//   return ret;
// }
// function isNumOrZero(num) {
//   // 数値でなかったら0にして返す
//   if( isNaN(num) ) { return 0; }
//   return num;
// }
// function showCountdown() {
//   // 現在日時を数値(1970-01-01 00:00:00からのミリ秒)に変換
//   var nowDate = new Date();
//   var dnumNow = nowDate.getTime();

//   // 指定日時を数値(1970-01-01 00:00:00からのミリ秒)に変換
//   var inputYear  = document.getElementById("userYear").value;
//   var inputMonth = document.getElementById("userMonth").value - 1;
//   var inputDate  = document.getElementById("userDate").value;
//   var inputHour  = document.getElementById("userHour").value;
//   var inputMin   = document.getElementById("userMin").value;
//   var inputSec   = document.getElementById("userSec").value;
//   var targetDate = new Date( isNumOrZero(inputYear), isNumOrZero(inputMonth), isNumOrZero(inputDate), isNumOrZero(inputHour), isNumOrZero(inputMin), isNumOrZero(inputSec) );
//   var dnumTarget = targetDate.getTime();

//   // 表示を準備
//   var dlYear  = targetDate.getFullYear();
//   var dlMonth = targetDate.getMonth() + 1;
//   var dlDate  = targetDate.getDate();
//   var dlHour  = targetDate.getHours();
//   var dlMin   = targetDate.getMinutes();
//   var dlSec   = targetDate.getSeconds();
//   var msg1 = "期限の" + dlYear + "/" + dlMonth + "/" + dlDate + " " + set2fig(dlHour) + ":" + set2fig(dlMin) + ":" + set2fig(dlSec);

//   // 引き算して日数(ミリ秒)の差を計算
//   var diff2Dates = dnumTarget - dnumNow;
//   if( dnumTarget < dnumNow ) {
//     // 期限が過ぎた場合は -1 を掛けて正の値に変換
//     diff2Dates *= -1;
//   }

//   // 差のミリ秒を、日数・時間・分・秒に分割
//   var dDays  = diff2Dates / ( 1000 * 60 * 60 * 24 );   // 日数
//   diff2Dates = diff2Dates % ( 1000 * 60 * 60 * 24 );
//   var dHour  = diff2Dates / ( 1000 * 60 * 60 );   // 時間
//   diff2Dates = diff2Dates % ( 1000 * 60 * 60 );
//   var dMin   = diff2Dates / ( 1000 * 60 );   // 分
//   diff2Dates = diff2Dates % ( 1000 * 60 );
//   var dSec   = diff2Dates / 1000;   // 秒
//   var msg2 = Math.floor(dDays) + "日"
//           + Math.floor(dHour) + "時間"
//           + Math.floor(dMin) + "分"
//           + Math.floor(dSec) + "秒";

//   // 表示文字列の作成
//   var msg;
//   if( dnumTarget > dnumNow ) {
//     // まだ期限が来ていない場合
//     msg = msg1 + "までは、あと" + msg2 + "です。";
//   }
//   else {
//     // 期限が過ぎた場合
//     msg = msg1 + "は、既に" + msg2 + "前に過ぎました。";
//   }

//   // 作成した文字列を表示
//   document.getElementById("RealtimeCountdownArea").innerHTML = msg;
//   document.getElementById("deadline.id").value =  targetDate;

// }
// // 1秒ごとに実行
// setInterval('showCountdown()',1000);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CountdownTimer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0233699884.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <!-- <a class="nav-link active" href="homes/index">Home</a> -->
        <%= link_to "Homes", homes_index_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Phrases", phrases_path, class: "nav-link"%>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user.id), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </body>

</html>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase) do |form| %>
  <% if phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
        <% phrase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :personage %>
    <%= form.text_field :personage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phrases</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Personage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.content %></td>
        <td><%= phrase.personage %></td>
        <td><%= link_to 'Show', phrase %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @phrase.content %>
</p>

<p>
  <strong>Personage:</strong>
  <%= @phrase.personage %>
</p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>

app/views/targets/_form.html.erb
<%= form_with(model: target) do |form| %>
  <% if target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
        <% target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :goal %>
    <%= form.text_field :goal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Targets</h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.age %></td>
        <td><%= target.goal %></td>
        <td><%= link_to 'Show', target %></td>
        <td><%= link_to 'Edit', edit_target_path(target) %></td>
        <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Target', new_target_path %>

app/views/targets/new.html.erb
<h1>New Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Back', targets_path %>

app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Age:</strong>
  <%= @target.age %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @target.goal %>
</p>

<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>

app/views/users/new.html.erb
<div class="container set_center_outer">
  <div class="set_center_inner">
    <h1>Sign up</h1>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %> 件のエラーが発生しました</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>
      <%= f.label :birthday %><br>
      <%= raw sprintf(f.date_select( :birthday, 
                                      default: { year: 1995, month: 1, day: 1 }, 
                                      use_month_numbers: true, 
                                      start_year: 2015, 
                                      end_year: 1960,
                                      date_separator: '%s'),
                                      '年', '月') + '日' %><br>
      <%= f.label :email %><br>
      <%= f.email_field :email %><br>
      <%= f.label :password %>(半角英数字6文字以上)<br>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %><br>
      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container set_center_outer">
  <div class="set_center_inner">
    <h2>プロフィールページ</h2>
    <p>お名前: <%= @user.name %></p>
    <p>誕生日: <%= @user.birthday %></p>
    <p>メールアドレス: <%= @user.email %></p>
  </div>
</div>